spring:
  application:
    name: ownAi

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      api-key: ${OPENROUTER_API_KEY}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: openai/gpt-4.1-mini
      embedding:
        options:
          model: text-embedding-3-small

server:
  port: 8080

logging:
  level:
    org.springframework.boot.context.config: DEBUG
