spring:
  application:
    name: ownAi

  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      api-key: ${OPENROUTER_API_KEY}
      base-url: https://openrouter.ai/api/v1
      chat:
        options:
          model: nvidia/nemotron-3-nano-30b-a3b:free
          max-tokens: 500
      embedding:
        options:
          model: text-embedding-3-small

server:
  port: 8080

logging:
  level:
    root: ERROR
    com.ownai: DEBUG
    org.springframework.web: DEBUG
    org.springframework.ai: ERROR
    com.zaxxer.hikari: DEBUG